title: Marco A.J. DeBellis
author: GitHub User
email: marcoajdebellis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I work at Sandy's as a delivery driver.
  I like to run in my free time.
  I want to be a corporate lawyer when I grow up.

# social links
instagram_username: realmarcoajdebellis

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
